
--1) Billing Table Creation 
CREATE TABLE IF NOT EXISTS BILLING AS 
(
	SELECT  
		CUST.FNAME
		,CUST.LNAME
		,SUM(
		CASE 
		WHEN US.DURATION <= 10 THEN 0.5 
		WHEN US.DURATION 	< 10 THEN 0.35
		END )AS COSTS
	FROM CUSTOMERS AS CUST
	JOIN USAGE AS US ON 1=1 
		AND CUST.USER_ID = US.USER_ID 
	GROUP BY CUST.FNAME,CUST.LNAME
);


--2) Top_Rider Table Creation 
CREATE TABLE IF NOT EXISTS Top_Riders AS
(
	SELECT 
		CONCAT (CUST.FNAME,' ',CUST.LNAME) AS NAME
		,COUNT(US.USER_ID) AS RIDES
	FROM CUSTOMERS AS CUST 
	JOIN USAGE AS US ON 1=1 
		AND CUST.USER_ID = US.USER_ID

	GROUP BY CONCAT  (CUST.FNAME,' ',CUST.LNAME)
	ORDER BY COUNT (US.USER_ID) DESC
	LIMIT 10
);

--3) Sum_by_Zip Table Creation 
CREATE TABLE IF NOT EXISTS Sum_by_Zip  AS 
(
	SELECT 
		COUNT(*) AS NUMBER 
		,ZIP 
	FROM CUSTOMERS
	GROUP BY ZIP 
	ORDER BY ZIP ASC
);